
export const countiesListMD = [
  'Allegany MD', 'Anne Arundel MD', 'Baltimore MD', 'Calvert MD', 'Caroline MD',
  'Carroll MD', 'Cecil MD', 'Charles MD', 'Dorchester MD', 'Frederick MD', 'Garrett MD',
  'Harford MD', 'Howard MD', 'Kent MD', 'Montgomery MD', 'Prince George\'s MD',
  'Queen Anne\'s MD', 'St. Mary\'s MD', 'Somerset MD', 'Talbot MD', 'Washington MD',
  'Wicomico MD', 'Worcester MD', 'Baltimore City MD',
];

export const countiesListDE = [
  'New Castle DE', 'Sussex DE', 'Kent DE'
];

export const countiesListVA = [
  'Accomack', 'Albemarle', 'Alexandria', 'Alleghany VA', 'Amelia', 'Amherst', 
  'Appomattox', 'Arlington', 'Augusta', 'Bath', 'Bedford', 'Bland',
   'Botetourt', 'Bristol', 'Brunswick', 'Buchanan', 'Buckingham', 'Buena Vista',
   'Campbell', 'Caroline VA', 'Carroll VA', 'Charles City',
   'Charlotte', 'Charlottesville', 'Chesapeake', 'Chesterfield', 'Clarke', 
   'Colonial Heights','Covington', 'Craig', 'Culpeper', 'Cumberland', 
   'Danville', 'Dickenson', 'Dinwiddie', 'Emporia', 'Essex', 'Fairfax',
   'Falls Church',  'Fauquier', 'Floyd', 'Fluvanna', 'Franklin', 'Franklin', 
   'Frederick VA', 'Fredericksburg', 
   'Galax', 'Giles', 'Gloucester', 'Goochland', 'Grayson', 'Greene VA', 
   'Greensville', 'Halifax', 'Hampton', 'Hanover', 'Harrisonburg'
   , 'Henrico', 'Henry', 'Highland', 'Hopewell', 'Isle of Wight', 
   'James City', 'King and Queen', 'King George', 'King William',
   'Lancaster', 'Lee', 'Lexington', 'Loudoun', 'Louisa', 'Lunenburg', 
   'Lynchburg', 'Madison', 'Manassas', 'Martinsville', 'Mathews', 
   'Mecklenburg', 'Middlesex', 'Montgomery VA', 'Nelson', 'New Kent', 'Newport News', 
   'Norfolk', 'Northampton VA', 'Northumberland', 'Norton', 'Nottoway', 
    'Orange', 'Page', 'Patrick', 'Petersburg', 'Pittsylvania', 'Poquoson', 
    'Portsmouth', 'Powhatan', 'Prince Edward', 'Prince George', 'Prince William',
    'Pulaski', 'Radford', 'Rappahannock', 'Richmond', 'Richmond', 'Roanoke', 
    'Rockbridge', 'Rockingham', 'Russell', 'Salem', 'Scott', 'Shenandoah',
     'Smyth', 'Southampton', 'Spotsylvania', 'Stafford', 'Staunton', 'Suffolk', 
     'Surry', 'Sussex VA', 'Tazewell', 'Virginia Beach', 'Warren', 'Washington VA', 
     'Waynesboro', 'Westmoreland', 'Williamsburg', 'Winchester', 
     'Wise', 'Wythe', 'York VA'];

export const countiesListWV = [
"Barbour", 
"Berkeley", 
"Boone",
"Braxton",
  "Brooke",
"Cabell",
"Calhoun",
"Clay",
"Doddridge",
"Fayette",
"Gilmer",
"Grant",
"Greenbrier",
"Hampshire",
"Hancock",
"Hardy",
"Harrison",
"Jackson",
"Jefferson",
"Kanawha",
"Lewis",
"Lincoln",
    "Logan",
    "Marion",
    "Marshall",
    "Mason",
    "McDowell",
    "Mercer",
    "Mineral",
    "Mingo",
    "Monongalia",
    "Monroe",
    "Morgan",
    "Nicholas",
    "Ohio",
    "Pendleton",
    "Pleasants",
    "Pocahontas",
    "Preston",
    "Putnam",
    "Raleigh",
    "Randolph",
    "Ritchie",
    "Roane",
    "Summers",
    "Taylor",
    "Tucker",
    "Tyler",
    "Upshur",
    "Wayne",
    "Webster",
    "Wetzel",
    "Wirt",
    "Wood",
    "Wyoming"];

export const countiesListPA = ["Adams",
"Allegheny",
"Armstrong",
"Beaver",
"Bedford",
"Berks",
"Blair",
"Bradford",
"Bucks",
"Butler",
"Cambria",
"Cameron",
"Carbon",
"Centre",
"Chester",
"Clarion",
"Clearfield",
"Clinton",
"Columbia PA",
"Crawford",
"Cumberland",
"Dauphin",
"Delaware",
"Elk",
"Erie",
"Fayette",
"Forest",
"Franklin",
"Fulton",
"Greene PA",
"Huntingdon",
"Indiana","Jefferson",
"Juniata",
"Lackawanna",
"Lancaster",
"Lawrence",
"Lebanon",
"Lehigh",
"Luzerne",
"Lycoming",
"McKean",
"Mercer",
"Mifflin",
"Monroe",
"Montgomery PA",
"Montour",
"Northampton PA",
"Northumberland",
"Perry",
"Philadelphia",
"Pike",
"Potter",
"Schuylkill",
"Snyder",
"Somerset PA",
"Sullivan",
"Susquehanna",
"Tioga",
"Union",
"Venango",
"Warren",
"Washington PA",
"Wayne",
"Westmoreland",
"Wyoming",
"York"]



