
export const countiesListMD = [
  'Allegany MD', 'Anne Arundel MD', 'Baltimore MD', 'Calvert MD', 'Caroline MD',
  'Carroll MD', 'Cecil MD', 'Charles MD', 'Dorchester MD', 'Frederick MD', 'Garrett MD',
  'Harford MD', 'Howard MD', 'Kent MD', 'Montgomery MD', 'Prince George\'s MD',
  'Queen Anne\'s MD', 'St. Mary\'s MD', 'Somerset MD', 'Talbot MD', 'Washington MD',
  'Wicomico MD', 'Worcester MD', 'Baltimore City MD',
];

export const countiesListDE = [
  'New Castle DE', 'Sussex DE', 'Kent DE'
];

export const countiesListVA = [
  'Accomack', 'Albemarle', 'Alexandria', 'Alleghany VA', 'Amelia', 'Amherst', 
  'Appomattox', 'Arlington', 'Augusta', 'Bath', 'Bedford VA', 'Bland',
   'Botetourt', 'Bristol', 'Brunswick', 'Buchanan', 'Buckingham', 'Buena Vista',
   'Campbell', 'Caroline VA', 'Carroll VA', 'Charles City',
   'Charlotte', 'Charlottesville', 'Chesapeake', 'Chesterfield', 'Clarke', 
   'Colonial Heights','Covington', 'Craig', 'Culpeper', 'Cumberland VA', 
   'Danville', 'Dickenson', 'Dinwiddie', 'Emporia', 'Essex', 'Fairfax',
   'Falls Church',  'Fauquier', 'Floyd', 'Fluvanna', 'Franklin County VA', 'Franklin City VA', 
   'Frederick VA', 'Fredericksburg', 
   'Galax', 'Giles', 'Gloucester', 'Goochland', 'Grayson', 'Greene VA', 
   'Greensville', 'Halifax', 'Hampton', 'Hanover', 'Harrisonburg'
   , 'Henrico', 'Henry', 'Highland', 'Hopewell', 'Isle of Wight', 
   'James City', 'King and Queen', 'King George', 'King William',
   'Lancaster VA', 'Lee', 'Lexington', 'Loudoun', 'Louisa', 'Lunenburg', 
   'Lynchburg', 'Madison', 'Manassas', 'Martinsville', 'Mathews', 
   'Mecklenburg', 'Middlesex', 'Montgomery VA', 'Nelson', 'New Kent', 'Newport News', 
   'Norfolk', 'Northampton VA', 'Northumberland VA', 'Norton', 'Nottoway', 
    'Orange', 'Page', 'Patrick', 'Petersburg', 'Pittsylvania', 'Poquoson', 
    'Portsmouth', 'Powhatan', 'Prince Edward', 'Prince George', 'Prince William',
    'Pulaski', 'Radford', 'Rappahannock', 'Richmond', 'Richmond', 'Roanoke', 
    'Rockbridge', 'Rockingham', 'Russell', 'Salem', 'Scott', 'Shenandoah',
     'Smyth', 'Southampton', 'Spotsylvania', 'Stafford', 'Staunton', 'Suffolk', 
     'Surry', 'Sussex VA', 'Tazewell', 'Virginia Beach', 'Warren VA', 'Washington VA', 
     'Waynesboro', 'Westmoreland VA', 'Williamsburg', 'Winchester', 
     'Wise', 'Wythe', 'York VA'];

export const countiesListWV = [
"Barbour", 
"Berkeley", 
"Boone",
"Braxton",
  "Brooke",
"Cabell",
"Calhoun",
"Clay",
"Doddridge",
"Fayette WV",
"Gilmer",
"Grant",
"Greenbrier",
"Hampshire",
"Hancock",
"Hardy",
"Harrison",
"Jackson",
"Jefferson WV",
"Kanawha",
"Lewis",
"Lincoln",
    "Logan",
    "Marion",
    "Marshall",
    "Mason",
    "McDowell",
    "Mercer WV",
    "Mineral",
    "Mingo",
    "Monongalia",
    "Monroe WV",
    "Morgan",
    "Nicholas",
    "Ohio",
    "Pendleton",
    "Pleasants",
    "Pocahontas",
    "Preston",
    "Putnam",
    "Raleigh",
    "Randolph",
    "Ritchie",
    "Roane",
    "Summers",
    "Taylor",
    "Tucker",
    "Tyler",
    "Upshur",
    "Wayne WV",
    "Webster",
    "Wetzel",
    "Wirt",
    "Wood",
    "Wyoming WV"];

export const countiesListPA = ["Adams",
"Allegheny",
"Armstrong",
"Beaver",
"Bedford PA",
"Berks",
"Blair",
"Bradford",
"Bucks",
"Butler",
"Cambria",
"Cameron",
"Carbon",
"Centre",
"Chester",
"Clarion",
"Clearfield",
"Clinton",
"Columbia PA",
"Crawford",
"Cumberland PA",
"Dauphin",
"Delaware",
"Elk",
"Erie",
"Fayette PA",
"Forest",
"Franklin PA",
"Fulton",
"Greene PA",
"Huntingdon",
"Indiana","Jefferson PA",
"Juniata",
"Lackawanna",
"Lancaster PA",
"Lawrence",
"Lebanon",
"Lehigh",
"Luzerne",
"Lycoming",
"McKean",
"Mercer PA",
"Mifflin",
"Monroe PA",
"Montgomery PA",
"Montour",
"Northampton PA",
"Northumberland PA",
"Perry",
"Philadelphia",
"Pike",
"Potter",
"Schuylkill",
"Snyder",
"Somerset PA",
"Sullivan",
"Susquehanna",
"Tioga",
"Union",
"Venango",
"Warren PA",
"Washington PA",
"Wayne PA",
"Westmoreland PA",
"Wyoming PA",
"York"]



